spring:
  datasource:
#    url: jdbc:postgresql://pgm-j6cm76z49d3e04939o.pg.rds.aliyuncs.com:1433/tds_simulation
#    username: srchain
#    password: 123456789
  url: jdbc:postgresql://192.168.1.188:5436/tds_simulation
  username: postgres
  password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # 打印 sql 语句
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'


server:
  port: 8082

sim:
  # jwt 配置
  jwt:
    # jwt token 有效时间 单位是秒
    expired-in: '25920000' # 登录有效时间 7 * 24 小时
    # 使用非对称加密算法 rs256, 自动生成私钥，公钥可以从服务器获取
    algorithm: 'rs256'
    private-key: ''

#logging:
#  level:
